### PR TITLE
Restructure and remove unnecessary files

### PR DESCRIPTION
**Pull request by diivm**

### CODE REVIEW

**Comment by kunaltyagi** [comment]
The structure was intended as follows:
* top-level
  * parser
  * language_binding
    * python specific
    * Future: JS specfic
  * frontend
    * cmake-file-api
    * compile-commands.json
  * misc
  * tests (or in respective folders?)

What's the aim of this restructuring?

**Comment by diivm** [comment]
Since we aim to make a general purpose tool (not specific to pcl), I think it would be better to design the project in a manner that other projects can import the `clang_bind` module and invoke accordingly.
We can use this tool in the main pcl repo for the bindings, and all hence pcl specific files such as cmake files, compile-commands.json, final bound modules, etc. needn't be a part of this repo.

Your thoughts?

**Review by kunaltyagi — COMMENTED** [review]
Do you think the content in the to be deleted readme should be moved into some other document (and generalized)?

While we do want to make a generic tool, we also want the testing ground to be PCL itself

**Comment by diivm** [comment]
> Do you think the content in the to be deleted readme should be moved into some other document (and generalized)?

Nah, that's old info, we'll rewrite the documentation/README

> While we do want to make a generic tool, we also want the testing ground to be PCL itself

What do you suggest? Keep the existing structure?

**Comment by kunaltyagi** [comment]
Just a comment. If there's a new README, LGTM to proceed

**Pull request merged**
